# LOGGING
logging:
  file: target/vedci.log
  level:
    org.vedci: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vedci
    username: vedci
    password: vedci
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

# SECURITY
security:
  password:
    secret: secret

# LIQUIBASE
liquibase:
  enabled: true
  change-log: classpath:liquibase/config/master.xml
  url: jdbc:postgresql://localhost:5432/vedci
  user: vedci
  password: vedci
